### ISSUE TITLE
502 Bad Gateway and config issues

### ISSUE THREAD

**Issue by robvadai** [Landoop/kafka-connect-ui#20]
Using the latest Confluent Kafka, Schema Registry etc versions (Confluent 3.1.2) I'm getting HTTP 502.

This is the same for KC UI and Schema Registry UI as well.

Snippet of my docker compose file:

```
schema-registry:
    image: confluentinc/cp-schema-registry
    hostname: schema-registry
    depends_on:
      - zookeeper
      - broker
    ports:
      - '8081:8081'
    environment:
      SCHEMA_REGISTRY_HOST_NAME: schema-registry
      SCHEMA_REGISTRY_KAFKASTORE_CONNECTION_URL: 'zookeeper:2181'
      SCHEMA_REGISTRY_ACCESS_CONTROL_ALLOW_METHODS: GET,POST,OPTIONS
      SCHEMA_REGISTRY_ACCESS_CONTROL_ALLOW_ORIGIN: '*'

  connect-ui:
    image: landoop/kafka-connect-ui
    hostname: connect-ui
    depends_on:
      - connect
    ports:
      - "8000:8000"
    environment:
      CONNECT_URL: 'http://connect:8083'

  schema-registry-ui:
    image: landoop/schema-registry-ui
    hostname: schema-registry-ui
    depends_on:
      - schema-registry
    ports:
      - "8001:8000"
    environment:
      SCHEMAREGISTRY_URL: 'http://schema-registry:8081'
      PROXY: 'true'
```
