### ISSUE TITLE
Overwrite the CORS Header witha docker-compose file

### ISSUE THREAD

**Issue by AngeloBadellino** [Landoop/kafka-connect-ui#78]
Having the followinf Docker-Compose

```
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    restart: unless-stopped
    ports:
      - "2181:2181"
    environment:
      - ZOOKEEPER_CLIENT_PORT=2181
      - ZOOKEEPER_TICK_TIME=2000

  kafka:
    image: confluentinc/cp-kafka:latest
    ports:
      - "59092:9092"
    environment:
      - KAFKA_BROKER_ID= 1
      - KAFKA_ZOOKEEPER_CONNECT= zookeeper:2181
      - KAFKA_ADVERTISED_LISTENERS= PLAINTEXT://kafka:9092
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR= 1
    depends_on:
      - zookeeper

  schema_registry:
    image: confluentinc/cp-schema-registry:latest
    ports:
      - '58081:8081'
    restart: unless-stopped
    environment:
      - SCHEMA_REGISTRY_LISTENERS= http://127.0.0.1:8081
      - SCHEMA_REGISTRY_HOST_NAME= schema
      - SCHEMA_REGISTRY_KAFKASTORE_CONNECTION_URL= zookeeper:2181
    depends_on:
      - kafka
      - zookeeper

  proxy:
    image: confluentinc/cp-kafka-rest:latest
    ports:
      - '58082:8082'
    environment:
      - KAFKA_REST_ZOOKEEPER_CONNECT= zookeeper:2181
      - KAFKA_REST_SCHEMA_REGISTRY_URL= schema:8081
      - KAFKA_REST_HOST_NAME= proxy
      - KAFKA_REST_LISTENERS= http://127.0.0.1:8082
    depends_on:
      - schema_registry
      - kafka
      - zookeeper

  kafka-ui:
    image: landoop/kafka-topics-ui:latest
    ports:
      - 58000:8000
    environment:
      - KAFKA_REST_PROXY_URL=http://127.0.0.1:8082
      - PROXY=True
    depends_on:
      - proxy
      - kafka
```
I am getting the CONNECTIVITY ERROR well know problem.
I am trying to figure out how to overwrite the kafka.rest.conf settings.

Any help?
